# Location of input files
client_data_path: input/client/client_data.csv
open_source_data_path: input/open_source

# type of screening: "pep", "sanction", "leaked papers"
type_screening: ["leaked papers"]

# train new model for tfidf-knn
train_model: true

# Location of the logging file
log_file: system.log

# Logging level
log_level: debug

# Yet to implement
# Location of output file