name: open_source_screening
channels:
  - conda-forge
  - defaults
dependencies:
  - unidecode=1.2.0
  - fuzzywuzzy=0.18.0
  - python=3.8.2
  - yaml=0.2.5
  - pandas=1.2.4
  - pip=23.0.1
  - pip:
    - scikit-learn==0.23.2
    - transliterate==1.10.2
    - numpy==1.22.4